import type { Metadata } from 'next';
import './globals.css';
import AppThemeProvider from '@/styles/theme';
import Header from '@/components/nav/Header';
import ReduxProvider from '@/store/provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppThemeProvider>
          <ReduxProvider>
            <Header />
            {children}
          </ReduxProvider>
        </AppThemeProvider>
      </body>
    </html>
  );
}
